### ISSUE TITLE
javadoc / API (for Extended Commands)

### ISSUE THREAD

**Issue by Mattenbrand** [magellan2/magellan2#14]
Da das _Extended Commands-Plugin_ (EC) auf die Magellan-API zurückgreift, ist eine entsprechende javadoc für EC-Benutzer ein wertvolles tool um komplexere und kreative Befehle erzeugen zu können.

**Comment by stm2** [comment]
Doc ist jetzt im Release enthalten.

Bugs und Featurerequests bitte auf https://magellan2.github.io/bugs/. Das hier ist derzeit nur für den internen Gebrauch.
