### ISSUE TITLE
Catapults are now carriages

### ISSUE THREAD

**Issue by Nugman** [magellan2/magellan2#39]
Since the end of last year, catapults are carriages with a transport capacity of 0GE when pulled by 2 horses or 4 trolls.

See Release Notes Eressea 28.4:
"Katapulte sind von jeher eine teure Waffe, die viel Holz benötigt, und nur schwer zu bewegen, wenn man nicht noch mehr Holz für Wagen aufwendet. Um sie ein wenig nützlicher zu machen, sind sie in Zukunft selbstfahrend: Ein Katapult ist selbst ein Fahrzeug, und kann wie ein Wagen von zwei Pferden gezogen werden, kann allerdings keine zusätzliche Last transportieren. Statt von zwei Pferden kann ein Katapult auch von vier Trollen gezogen werden."

Can this new behaviour be handled in Magellan?

**Comment by trickert76** [comment]
Merged
