### ISSUE TITLE
Make HTTPClient timeout (5 seconds) customizable

### ISSUE THREAD

**Issue by fantasya-pbem** [magellan2/magellan2#43]
When uploading orders to the server via HTTP client, a fixed timeout of five seconds is set:

https://github.com/magellan2/magellan2/blob/master/src-library/magellan/library/utils/HTTPClient.java#L101

In [Fantasya](https://www.fantasya-pbem.de) we have implemented a server upload endpoint, but our extensive check sometimes takes longer than those five seconds and Magellan runs into the timeout and shows the timeout error message.

Please make this value changeable, either by adding an input field to the server upload form or by adding a Magellan configuration INI option in `magellan.ini:OrderWriter.serverTimeout`.

**Comment by trickert76** [comment]
Can you have a look at the review and check, if 0 is a good default value for time out here?

**Comment by trickert76** [comment]
Can you update the PR? Then I'll do the merge. I'm working on a new release. Let's see, if I can do it after so many years.
